name: Java CI with Maven

# Sự kiện trigger workflow: khi push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Máy ảo chạy workflow là Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '22'

      # Bước 3: Build và chạy test
      - name: Build with Maven and run tests
        run: mvn clean test
